FROM ubuntu:latest

LABEL "Maintainer"="BJlearn"

WORKDIR /root/hello-world
COPY HelloWorld.java /root/hello-world

RUN apt-get update && apt-get install -y openjdk-8-jdk
ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
ENV PATH $PATH:$JAVA_HOME/bin

RUN javac HelloWorld.java

ENTRYPOINT java HelloWorld